/** Country list for seeding — used by npm run seed:countries */
export const SEED_COUNTRIES = [
  { name: 'Afghanistan', code: 'AF', dial_code: '+93' },
  { name: 'Albania', code: 'AL', dial_code: '+355' },
  { name: 'Algeria', code: 'DZ', dial_code: '+213' },
  { name: 'Argentina', code: 'AR', dial_code: '+54' },
  { name: 'Australia', code: 'AU', dial_code: '+61' },
  { name: 'Austria', code: 'AT', dial_code: '+43' },
  { name: 'Bahrain', code: 'BH', dial_code: '+973' },
  { name: 'Bangladesh', code: 'BD', dial_code: '+880' },
  { name: 'Belgium', code: 'BE', dial_code: '+32' },
  { name: 'Brazil', code: 'BR', dial_code: '+55' },
  { name: 'Canada', code: 'CA', dial_code: '+1' },
  { name: 'China', code: 'CN', dial_code: '+86' },
  { name: 'Denmark', code: 'DK', dial_code: '+45' },
  { name: 'Egypt', code: 'EG', dial_code: '+20' },
  { name: 'Finland', code: 'FI', dial_code: '+358' },
  { name: 'France', code: 'FR', dial_code: '+33' },
  { name: 'Germany', code: 'DE', dial_code: '+49' },
  { name: 'Greece', code: 'GR', dial_code: '+30' },
  { name: 'Hong Kong', code: 'HK', dial_code: '+852' },
  { name: 'India', code: 'IN', dial_code: '+91' },
  { name: 'Indonesia', code: 'ID', dial_code: '+62' },
  { name: 'Iran', code: 'IR', dial_code: '+98' },
  { name: 'Iraq', code: 'IQ', dial_code: '+964' },
  { name: 'Ireland', code: 'IE', dial_code: '+353' },
  { name: 'Italy', code: 'IT', dial_code: '+39' },
  { name: 'Japan', code: 'JP', dial_code: '+81' },
  { name: 'Jordan', code: 'JO', dial_code: '+962' },
  { name: 'Kenya', code: 'KE', dial_code: '+254' },
  { name: 'Kuwait', code: 'KW', dial_code: '+965' },
  { name: 'Lebanon', code: 'LB', dial_code: '+961' },
  { name: 'Malaysia', code: 'MY', dial_code: '+60' },
  { name: 'Maldives', code: 'MV', dial_code: '+960' },
  { name: 'Mexico', code: 'MX', dial_code: '+52' },
  { name: 'Morocco', code: 'MA', dial_code: '+212' },
  { name: 'Nepal', code: 'NP', dial_code: '+977' },
  { name: 'Netherlands', code: 'NL', dial_code: '+31' },
  { name: 'New Zealand', code: 'NZ', dial_code: '+64' },
  { name: 'Nigeria', code: 'NG', dial_code: '+234' },
  { name: 'Norway', code: 'NO', dial_code: '+47' },
  { name: 'Oman', code: 'OM', dial_code: '+968' },
  { name: 'Pakistan', code: 'PK', dial_code: '+92' },
  { name: 'Philippines', code: 'PH', dial_code: '+63' },
  { name: 'Poland', code: 'PL', dial_code: '+48' },
  { name: 'Portugal', code: 'PT', dial_code: '+351' },
  { name: 'Qatar', code: 'QA', dial_code: '+974' },
  { name: 'Russia', code: 'RU', dial_code: '+7' },
  { name: 'Saudi Arabia', code: 'SA', dial_code: '+966' },
  { name: 'Singapore', code: 'SG', dial_code: '+65' },
  { name: 'South Africa', code: 'ZA', dial_code: '+27' },
  { name: 'South Korea', code: 'KR', dial_code: '+82' },
  { name: 'Spain', code: 'ES', dial_code: '+34' },
  { name: 'Sri Lanka', code: 'LK', dial_code: '+94' },
  { name: 'Sweden', code: 'SE', dial_code: '+46' },
  { name: 'Switzerland', code: 'CH', dial_code: '+41' },
  { name: 'Syria', code: 'SY', dial_code: '+963' },
  { name: 'Thailand', code: 'TH', dial_code: '+66' },
  { name: 'Turkey', code: 'TR', dial_code: '+90' },
  { name: 'Ukraine', code: 'UA', dial_code: '+380' },
  { name: 'United Arab Emirates', code: 'AE', dial_code: '+971' },
  { name: 'United Kingdom', code: 'GB', dial_code: '+44' },
  { name: 'United States', code: 'US', dial_code: '+1' },
  { name: 'Vietnam', code: 'VN', dial_code: '+84' },
  { name: 'Yemen', code: 'YE', dial_code: '+967' },
] as const;
