/** Major Pakistan cities — used by npm run seed:cities */
export const SEED_PAKISTAN_CITIES = [
  'Karachi',
  'Lahore',
  'Islamabad',
  'Rawalpindi',
  'Faisalabad',
  'Multan',
  'Peshawar',
  'Quetta',
  'Hyderabad',
  'Sialkot',
  'Gujranwala',
  'Sargodha',
  'Bahawalpur',
  'Sukkur',
  'Larkana',
  'Sheikhupura',
  'Jhang',
  'Rahim Yar Khan',
  'Gujrat',
  'Kasur',
  'Mardan',
  'Mingora',
  'Nawabshah',
  'Sahiwal',
  'Okara',
  'Mirpur Khas',
  'Chiniot',
  'Kamoke',
  'Hafizabad',
  'Kohat',
  'Jacobabad',
  'Shikarpur',
  'Muzaffargarh',
  'Khanewal',
  'Gojra',
  'Mandi Bahauddin',
  'Abbottabad',
  'Turbat',
  'Dadu',
  'Khairpur',
  'Pakpattan',
  'Tando Adam',
  'Jhelum',
  'Dera Ghazi Khan',
  'Muzaffarabad',
  'Gilgit',
  'Skardu',
  'Gwadar',
  'Attock',
  'Wah Cantonment',
] as const;
